default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: zygo_rails_challenge_development

test:
  <<: *default
  database: zygo_rails_challenge_test

production:
  <<: *default
  database: zygo_rails_challenge_production
  username: zygo_rails_challenge
  password: <%= ENV['ZYGO_RAILS_CHALLENGE_DATABASE_PASSWORD'] %>
